Configuratron:
  preload: True

use_gpu: False
deep1010: False

datasets:
  sleepedf:
    name: "sleepedf"
    toplevel: '/path/to/data/'
    events: {'Sleep stage W': 0, 'Sleep stage 1': 1, 'Sleep stage 2': 2, 'Sleep stage 3': 3, 'Sleep stage 4': 3, 'Sleep stage R': 4}
    tmin: 0
    tlen: 30
    test_size: 0.2
    val_size: 0.25
    chunk_duration: '30'
    exclude_channels: ['Event marker']
    preload: True
    picks: ['EEG Fpz-Cz', 'EEG Pz-Oz']
    deep1010: False
    rename_channels: 
      FPZ: 'EEG Fpz-Cz'
      PZ: 'EEG Pz-Oz'
    #toplevel: /Users/theb/Desktop/physionet.org/physionet.org/files/challenge-2018/1.0.0/training/∂
    train_params:
      epochs: 7
      batch_size: 4
    lr: 0.0001
    folds: 5
